# Generated by Django 5.2.5 on 2025-08-28 19:11

import counseling_backend.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counseling_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', counseling_backend.models.CustomUserManager()),
            ],
        ),
    ]
